/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 12 22:24:18 GMT 2023
 */

package org.example.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Flight;
import org.example.Time;
import org.example.filter.CostRangeFilter;
import org.example.filter.Input;
import org.example.filter.OriginDestinationFilter;
import org.example.filter.TimeSpanFilter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Filter_ESTest extends Filter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      Time time0 = new Time(3906, 0);
      Input input0 = new Input("H5#U{^VpLA^stGd", "@w%6YC7~{#mW", "@w%6YC7~{#mW", (-1367.79), (-1367.79), true, false, 0, time0, time0, true, false);
      timeSpanFilter0.read(input0);
      assertEquals("H5#U{^VpLA^stGd", input0.getAirline());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      boolean boolean0 = timeSpanFilter0.apply(linkedList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CostRangeFilter costRangeFilter0 = new CostRangeFilter();
      boolean boolean0 = costRangeFilter0.apply((List<Flight>) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CostRangeFilter costRangeFilter0 = new CostRangeFilter();
      // Undeclared exception!
      try { 
        costRangeFilter0.read((Input) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.filter.CostRangeFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CostRangeFilter costRangeFilter0 = new CostRangeFilter();
      Time time0 = new Time();
      Input input0 = new Input("org.example.filter.TimeSpanFilter", "org.example.filter.TimeSpanFilter", "org.example.filter.TimeSpanFilter", (-1671.87481), (-1671.87481), true, true, (-831), time0, time0, false, false);
      costRangeFilter0.read(input0);
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      // Undeclared exception!
      try { 
        costRangeFilter0.apply(linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.filter.CostRangeFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      OriginDestinationFilter originDestinationFilter0 = new OriginDestinationFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      // Undeclared exception!
      try { 
        originDestinationFilter0.apply(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.filter.OriginDestinationFilter", e);
      }
  }
}
