/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 12 22:22:28 GMT 2023
 */

package org.example.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Flight;
import org.example.Time;
import org.example.filter.Input;
import org.example.filter.TimeSpanFilter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TimeSpanFilter_ESTest extends TimeSpanFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      List<Flight> list0 = linkedList0.subList(0, 0);
      Flight flight0 = new Flight((-379));
      linkedList0.add(flight0);
      // Undeclared exception!
      try { 
        timeSpanFilter0.apply(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      linkedList0.add((Flight) null);
      // Undeclared exception!
      try { 
        timeSpanFilter0.apply(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.filter.TimeSpanFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      Flight flight0 = new Flight((-379));
      linkedList0.add(flight0);
      boolean boolean0 = timeSpanFilter0.apply(linkedList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      Time time0 = new Time();
      Input input0 = new Input((String) null, "", "", 1528.84153364474, 850.054242152513, true, true, (-379), time0, time0, true, true);
      timeSpanFilter0.read(input0);
      boolean boolean0 = timeSpanFilter0.apply(linkedList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      Time time0 = new Time();
      Input input0 = new Input("iQ", "iQ", "iQ", (-1.0), (-1.0), false, false, (-1), time0, time0, false, false);
      timeSpanFilter0.read(input0);
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      boolean boolean0 = timeSpanFilter0.apply(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      Time time0 = new Time((-1), (-1));
      Input input0 = new Input("NM  Cz\"V|a;UI", "NM  Cz\"V|a;UI", "NM  Cz\"V|a;UI", (-1), (-1), true, true, (-1), time0, time0, true, true);
      timeSpanFilter0.read(input0);
      // Undeclared exception!
      try { 
        timeSpanFilter0.apply(linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.filter.TimeSpanFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      LinkedList<Flight> linkedList0 = new LinkedList<Flight>();
      Time time0 = new Time((-1), (-1));
      Input input0 = new Input("", "", "", 2660.9, 2660.9, true, true, (-1), time0, time0, false, true);
      timeSpanFilter0.read(input0);
      // Undeclared exception!
      try { 
        timeSpanFilter0.apply(linkedList0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.filter.TimeSpanFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TimeSpanFilter timeSpanFilter0 = new TimeSpanFilter();
      // Undeclared exception!
      try { 
        timeSpanFilter0.read((Input) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.filter.TimeSpanFilter", e);
      }
  }
}
